import * as React from 'react';
import TextField from '@mui/material/TextField';
import Autocomplete from '@mui/material/Autocomplete';

export default function ComboBox() {
  return (
    <Autocomplete
      disablePortal
      id="combo-box-demo"
      options={cseclasses}
      sx={{ width: 500 }}
      renderInput={(params) => <TextField {...params} label="Class" />}
    />
  );
}

// Top 100 films as rated by IMDb users. http://www.imdb.com/chart/top
const cseclasses = [
  {label : 'AM 114 Introduction to Dynamical Systems'},
{label : 'AM 147 Computational Methods and Applications'},
{label : 'CMPM 120 Game Development Experience'},
{label : 'CMPM 131 User Experience for Interactive Media'},
{label : 'CMPM 146 Game AI'},
{label : 'CMPM 163 Game Graphics and Real-Time Rendering'},
{label : 'CMPM 164 Game Engines'},
{label : 'CMPM 171 Game Design Studio II'},
{label : 'CMPM 172 Game Design Studio III'},
{label : 'CSE 10 Introduction to Computer Science'},
{label : 'CSE 100 Logic Design'},
{label : 'CSE 101 Introduction to Data Structures and Algorithms'},
{label : 'CSE 102 Introduction to Analysis of Algorithms'},
{label : 'CSE 103 Computational Models'},
{label : 'CSE 104 Computability and Computational Complexity'},
{label : 'CSE 106 Applied Graph Theory and Algorithms'},
{label : 'CSE 107 Probability and Statistics for Engineers'},
{label : 'CSE 108 Algorithmic Foundations of Cryptography'},
{label : 'CSE 110A Fundamentals of Compiler Design I'},
{label : 'CSE 110B Fundamentals of Compiler Design II'},
{label : 'CSE 111 Advanced Programming'},
{label : 'CSE 112 Comparative Programming Languages'},
{label : 'CSE 113 Parallel and Concurrent Programming'},
{label : 'CSE 114A Foundations of Programming Languages'},
{label : 'CSE 114B Functional Programming'},
{label : 'CSE 115A Introduction to Software Engineering'},
{label : 'CSE 115B Software Design Project'},
{label : 'CSE 115C Software Design Project II'},
{label : 'CSE 115D Software Design Project - Accelerated'},
{label : 'CSE 117 Open Source Programming'},
{label : 'CSE 118 Mobile Applications'},
{label : 'CSE 119 Software for Society'},
{label : 'CSE 12 Computer Systems and Assembly Language and Lab'},
{label : 'CSE 120 Computer Architecture'},
{label : 'CSE 121 Embedded System Design'},
{label : 'CSE 122 Introduction to VLSI Digital System Design'},
{label : 'CSE 123A Engineering Design Project I'},
{label : 'CSE 123B Engineering Design Project II'},
{label : 'CSE 125 Logic Design with Verilog'},
{label : 'CSE 129A Capstone Project I'},
{label : 'CSE 129B Capstone Project II'},
{label : 'CSE 129C Capstone Project III'},
{label : 'CSE 130 Principles of Computer Systems Design'},
{label : 'CSE 132 Computer Security'},
{label : 'CSE 134 Embedded Operating Systems'},
{label : 'CSE 138 Distributed Systems'},
{label : 'CSE 13S Computer Systems and C Programming'},
{label : 'CSE 140 Artificial Intelligence'},
{label : 'CSE 142 Machine Learning'},
{label : 'CSE 143 Introduction to Natural Language Processing'},
{label : 'CSE 144 Applied Machine Learning'},
{label : 'CSE 145 Introduction to Data Mining'},
{label : 'CSE 146 Ethics and Algorithms'},
{label : 'CSE 150 Introduction to Computer Networks'},
{label : 'CSE 151 Advanced Computer Networks'},
{label : 'CSE 152 Principles of Computer Communication'},
{label : 'CSE 156 Network Programming'},
{label : 'CSE 157 Internet of Things'},
{label : 'CSE 16 Applied Discrete Mathematics'},
{label : 'CSE 160 Introduction to Computer Graphics'},
{label : 'CSE 161 Introduction to Data Visualization'},
{label : 'CSE 162 Advanced Computer Graphics and Animation'},
{label : 'CSE 163 Data Programming for Visualization'},
{label : 'CSE 165 Human-Computer Interaction'},
{label : 'CSE 167 Mobile Sensing and Interaction'},
{label : 'CSE 168 Introduction to Augmented Reality and Virtual Reality'},
{label : 'CSE 180 Database Systems I'},
{label : 'CSE 181 Database Systems II'},
{label : 'CSE 182 Introduction to Database Management Systems'},
{label : 'CSE 183 Web Applications'},
{label : 'CSE 184 Data Wrangling and Web Scraping'},
{label : 'CSE 185E Technical Writing for Computer Science and Engineering'},
{label : 'CSE 191 Computer Science and Technology Seminar'},
{label : 'CSE 192 Supervised Student Teaching/Tutoring'},
{label : 'CSE 193 Field Study'},
{label : 'CSE 194 Group Tutorial'},
{label : 'CSE 195 Senior Thesis Research'},
{label : 'CSE 198 Individual Study or Research'},
{label : 'CSE 199 Tutorial'},
{label : 'CSE 20 Beginning Programming in Python'},
{label : 'CSE 200 Research and Teaching in Computer Science and Engineering'},
{label : 'CSE 201 Analysis of Algorithms'},
{label : 'CSE 202 Combinatorial Algorithms'},
{label : 'CSE 204 Computational Models and Complexity'},
{label : 'CSE 205 Logic in Computer Science'},
{label : 'CSE 207 Graph Algorithms'},
{label : 'CSE 210A Programming Languages'},
{label : 'CSE 210B Advanced Programming Languages'},
{label : 'CSE 211 Compiler Design'},
{label : 'CSE 212A Software Engineering'},
{label : 'CSE 212B Software Reuse and Component-Based Software Engineering'},
{label : 'CSE 214 Principles of Database Systems'},
{label : 'CSE 215 Design and Implementation of Database Systems'},
{label : 'CSE 216 Formal Methods'},
{label : 'CSE 220 Computer Architecture'},
{label : 'CSE 221 Advanced Microprocessor Design'},
{label : 'CSE 222A VLSI Digital System Design'},
{label : 'CSE 222B VLSI System-on-a-Chip Design'},
{label : 'CSE 225 Introduction to ASIC Systems Design'},
{label : 'CSE 226 Advanced Parallel Processing'},
{label : 'CSE 229 Field-Programmable Gate Arrays Computer-Assisted Design'},
{label : 'CSE 231 Advanced Operating Systems'},
{label : 'CSE 232 Distributed Systems'},
{label : 'CSE 233 Advanced Computer Security'},
{label : 'CSE 234 Understanding Cryptography'},
{label : 'CSE 235 Cyber-Physical Systems Security'},
{label : 'CSE 237 Storage Systems'},
{label : 'CSE 240 Artificial Intelligence'},
{label : 'CSE 241 Knowledge Engineering'},
{label : 'CSE 242 Machine Learning'},
{label : 'CSE 243 Data Mining'},
{label : 'CSE 244A Foundations of Deep Learning'},
{label : 'CSE 244B Machine Learning for Natural Language Processing'},
{label : 'CSE 245 Computational Models of Discourse and Dialogue'},
{label : 'CSE 246 Responsible Data Science'},
{label : 'CSE 247 Projects in Artificial Intelligence'},
{label : 'CSE 248 Foundations of Data Science'},
{label : 'CSE 249 Large-Scale Web Analytics and Machine Learning'},
{label : 'CSE 250A Computer Networks'},
{label : 'CSE 250B Principles of Computer Communication'},
{label : 'CSE 250C High Speed Computer Networks'},
{label : 'CSE 253 Network Security'},
{label : 'CSE 257 Wireless and Mobile Networks'},
{label : 'CSE 259 Sensor Networks'},
{label : 'CSE 260 Computer Graphics'},
{label : 'CSE 261 Advanced Visualization'},
{label : 'CSE 262 Computer Animation'},
{label : 'CSE 263 Data Driven Discovery and Visualization'},
{label : 'CSE 264 Computer Vision'},
{label : 'CSE 265 Human-Computer Interaction'},
{label : 'CSE 272 Information Retrieval'},
{label : 'CSE 276 Optimization Theory and Applications'},
{label : 'CSE 277 Random Process Models in Engineering'},
{label : 'CSE 279 Data Mining and Business Analytics in Knowledge Services'},
{label : 'CSE 280A Seminar in Computer Science and Engineering'},
{label : 'CSE 280D Seminar in Database Systems'},
{label : 'CSE 280F Seminar on Software Engineering'},
{label : 'CSE 280G VLSI/CAD Seminar'},
{label : 'CSE 280H Seminar in Human Computation Systems'},
{label : 'CSE 280I Seminar on Information Retrieval and Knowledge Management'},
{label : 'CSE 280J Seminar on Computer Graphics'},
{label : 'CSE 280K Sales and Marketing for Technologists and Engineers'},
{label : 'CSE 280L Seminar on Logic in Computer Science'},
{label : 'CSE 280M Seminar on Machine Learning'},
{label : 'CSE 280N Seminar on Networks'},
{label : 'CSE 280O Seminar in Applied Programming Languages'},
{label : 'CSE 280P Seminar on Parallel Processing'},
{label : 'CSE 280S Seminar on Computer Systems'},
{label : 'CSE 280T Seminar on New Technologies'},
{label : 'CSE 280V Seminar on Computer Vision'},
{label : 'CSE 280X Seminar in Distributed Systems'},
{label : 'CSE 280Z Seminar in Natural Language Processing and Dialogue'},
{label : 'CSE 285 Technical Writing for Engineering Graduates'},
{label : 'robabilistic Algorithms and Average Case Analysis'},
{label : 'CSE 290C Advanced Topics in Machine Learning'},
{label : 'CSE 290D Neural Computation'},
{label : 'CSE 290E Object-Oriented Programming Methodology'},
{label : 'CSE 290F Applications of Combinatorics'},
{label : 'CSE 290G Topics in Software Engineering'},
{label : 'CSE 290H Topics in Database Systems'},
{label : 'CSE 290J Advanced Topics in Computer Graphics and Visual Computing'},
{label : 'CSE 290K Advanced Topics in Natural Language Processing'},
{label : 'CSE 290L Topics in Crowdsourcing and Collaboration'},
{label : 'CSE 290M Topics in Parallel Computation'},
{label : 'CSE 290N Topics in Computer Performance'},
{label : 'CSE 290O Algorithmic Foundations of Convex Optimization'},
{label : 'CSE 290P Data Privacy Via Machine Learning, and Back'},
{label : 'CSE 290Q Topics in Programming Languages'},
{label : 'CSE 290S Advanced Topics in Computer Systems'},
{label : 'CSE 290T Topics in Computing for Society'},
{label : 'CSE 290X Cryptography and Computer Security'},
{label : 'CSE 293 Advanced Topics in Computer Science &amp; Engineering'},
{label : 'CSE 296 Masters Project'},
{label : 'CSE 297A Individual Study or Research'},
{label : 'CSE 297B Individual Study or Research'},
{label : 'CSE 297C Individual Study or Research'},
{label : 'CSE 297F Independent Study or Research'},
{label : 'CSE 299A Thesis Research'},
{label : 'CSE 299B Thesis Research'},
{label : 'CSE 299C Thesis Research'},
{label : 'CSE 299F Thesis Research'},
{label : 'oftware and Hardware'},
{label : 'ython'},
{label : 'ata Analysis and Empirical Methods'},
{label : 'CSE 5J Introduction to Programming in Java'},
{label : 'isability, Technology, and Society'},
{label : 'CSE 80L Social Data Analytics and Visualization'},
{label : 'CSE 80N Introduction to Networking and the Internet'},
{label : 'CSE 80S Social Networks'},
{label : 'CSE 94 Group Tutorial'},
{label : 'CSE 94F Group Tutorial'},
{label : 'CSE 99 Tutorial'},
{label : 'CSE 99F Tutorial'},
{label : 'ECE 253 Introduction to Information Theory'},
{label : 'ECON 166A Game Theory and Applications I'},
{label : 'ECON 166B Game Theory and Applications II'},
{label : 'ECON 272 Evolutionary Game Theory'},
{label : 'MATH 110 Introduction to Number Theory'},
{label : 'MATH 115 Graph Theory'},
{label : 'MATH 116 Combinatorics'},
{label : 'MATH 117 Advanced Linear Algebra'},
{label : 'MATH 118 Advanced Number Theory'},
{label : 'MATH 134 Cryptography'},
{label : 'MATH 145 Introductory Chaos Theory'},
{label : 'MATH 148 Numerical Analysis'},
{label : 'MATH 160 Mathematical Logic I'},
{label : 'MATH 161 Mathematical Logic II'},
{label : 'STAT 132 Classical and Bayesian Inference'},
{label : 'STAT 266A Data Visualization and Statistical Programming in R'},
{label : 'STAT 266B Advanced Statistical Programming in R'},
{label : 'STAT 266C Introduction to Data Wrangling'},
];
